create table "public"."solve_times" (
    "id" bigint generated by default as identity not null,
    "time" bigint not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."solve_times" enable row level security;

CREATE UNIQUE INDEX solve_times_pkey ON public.solve_times USING btree (id);

alter table "public"."solve_times" add constraint "solve_times_pkey" PRIMARY KEY using index "solve_times_pkey";

alter table "public"."solve_times" add constraint "solve_times_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) not valid;

alter table "public"."solve_times" validate constraint "solve_times_user_id_fkey";


