create table "public"."oll" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "oll_group_id" bigint not null
);


create table "public"."oll_group" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


create table "public"."oll_scramble" (
    "id" bigint generated by default as identity not null,
    "oll_id" bigint not null,
    "scramble" text
);


CREATE UNIQUE INDEX oll_group_pkey ON public.oll_group USING btree (id);

CREATE UNIQUE INDEX oll_pkey ON public.oll USING btree (id);

CREATE UNIQUE INDEX oll_scramble_pkey ON public.oll_scramble USING btree (id);

alter table "public"."oll" add constraint "oll_pkey" PRIMARY KEY using index "oll_pkey";

alter table "public"."oll_group" add constraint "oll_group_pkey" PRIMARY KEY using index "oll_group_pkey";

alter table "public"."oll_scramble" add constraint "oll_scramble_pkey" PRIMARY KEY using index "oll_scramble_pkey";

alter table "public"."oll" add constraint "oll_oll_group_id_fkey" FOREIGN KEY (oll_group_id) REFERENCES oll_group(id) not valid;

alter table "public"."oll" validate constraint "oll_oll_group_id_fkey";

alter table "public"."oll_scramble" add constraint "oll_scramble_oll_id_fkey" FOREIGN KEY (oll_id) REFERENCES oll(id) not valid;

alter table "public"."oll_scramble" validate constraint "oll_scramble_oll_id_fkey";


