name: CI
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx affected --target=build-storybook --parallel=3
      - run: npx nx run cube-trainer:build
      - run: npx cap sync
      - run: cp apps/cube-trainer/.env.example apps/cube-trainer/.env
      - run: cp apps/cube-trainer/.env.e2e.example apps/cube-trainer/.env.e2e
      - run: npm run supabase:start
      - run: npx playwright install --with-deps
      - run: npx nx affected --target=test --parallel=3
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/cube-trainer/playwright-report/
          retention-days: 30
