name: CI
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
      - run: npx cap sync
      - run: cp apps/cube-trainer/.env.example apps/cube-trainer/.env
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: supabase start
      - run: supabase db reset
      - run: npx nx affected --target=e2e --parallel=3
